### ISSUE TITLE
P values missing scientific notation

### ISSUE THREAD

**Issue by kshefchek** [PriceLab/translator-bigquery-api#2]
When querying the big gim api, I see many p values >1.  For example, 

http://biggim.ncats.io/api/interactions/query?table=BigGIM_70_v1&ids1=3981&ids2=2175,2187,2176,2178,2188,2189,55120&format=json

and the column: TCGA_BLCA_Pvalue

cc @JohnCEarls @putmantime

**Comment by JohnCEarls** [comment]
The pvalues are negative log10.

Best,

John C. Earls

https://plus.google.com/107716712696040682614/about

*We can only see a short distance ahead, but we can see plenty there that
needs to be done.*

--Alan Turing

**Comment by kshefchek** [comment]
Makes sense, thanks!
